if not BETTERUI.Inventory then BETTERUI.Inventory = {} end
if not BETTERUI.Inventory.CONST then BETTERUI.Inventory.CONST = {} end

BETTERUI.Inventory.CONST.DIALOG_QUEUE_TIMEOUT_MS = 300
BETTERUI.Inventory.CONST.TOOLTIP_REFRESH_DELAY_MS = BETTERUI.CIM.CONST.TIMING.TOOLTIP_REFRESH_DELAY_MS

BETTERUI.Inventory.CONST.CATEGORY_ITEM_ACTION_MODE = 1
BETTERUI.Inventory.CONST.ITEM_LIST_ACTION_MODE = 2
BETTERUI.Inventory.CONST.CRAFT_BAG_ACTION_MODE = 3

BETTERUI.Inventory.CONST.LIST_TYPES = {
    CATEGORY = "categoryList",
    ITEM = "itemList",
    CRAFT_BAG = "craftBagList",
}

BETTERUI.CIM.DeprecationRegistry.Register(
    "INVENTORY_CATEGORY_LIST",
    "BETTERUI.Inventory.CONST.LIST_TYPES.CATEGORY",
    "v3.1"
)
BETTERUI.CIM.DeprecationRegistry.Register(
    "INVENTORY_ITEM_LIST",
    "BETTERUI.Inventory.CONST.LIST_TYPES.ITEM",
    "v3.1"
)
BETTERUI.CIM.DeprecationRegistry.Register(
    "INVENTORY_CRAFT_BAG_LIST",
    "BETTERUI.Inventory.CONST.LIST_TYPES.CRAFT_BAG",
    "v3.1"
)

BETTERUI.Inventory.CONST.DEBOUNCE_MS = BETTERUI.CIM.CONST.TIMING.DEBOUNCE_MS
BETTERUI.Inventory.CONST.CATEGORY_REFRESH_DELAY_MS = BETTERUI.CIM.CONST.TIMING.CATEGORY_CHANGE_DELAY_MS
BETTERUI.Inventory.CONST.BATCH_SIZE_INITIAL = BETTERUI.CIM.CONST.TIMING.BATCH_SIZE_INITIAL
BETTERUI.Inventory.CONST.BATCH_SIZE_REMAINING = BETTERUI.CIM.CONST.TIMING.BATCH_SIZE_REMAINING

BETTERUI.Inventory.CONST.LIST_ENTRY_BASE_FONT_SIZE = 24
BETTERUI.Inventory.CONST.LIST_ENTRY_BASE_ICON_SIZE = 34
BETTERUI.Inventory.CONST.LIST_ENTRY_BASE_ICON_OFFSET = -42
BETTERUI.Inventory.CONST.LIST_ENTRY_ICON_OFFSET_FACTOR = 0.4

BETTERUI.Inventory.CONST.STATUS_INDICATOR_OFFSET_X = -2
BETTERUI.Inventory.CONST.EQUIPPED_ICON_OFFSET_X = -2

BETTERUI.Inventory.CONST.ICON_SIZE_SMALL = 16
BETTERUI.Inventory.CONST.ICON_SIZE_MEDIUM = 24
BETTERUI.Inventory.CONST.ICON_SIZE_LARGE = 34

BETTERUI.Inventory.CONST.EQUIP_ICON_BASE_WIDTH = 28
BETTERUI.Inventory.CONST.EQUIP_ICON_BASE_HEIGHT = 24

BETTERUI.Inventory.CONST.SORT_SCHEMA = BETTERUI.CIM.CONST.SORT_SCHEMA
BETTERUI.Inventory.DefaultSortComparator = BETTERUI.CIM.Utils.DefaultSortComparator
